name: Cloud Custodian Policies

on:
  push:
    branches:
      - test-release
  pull_request:
    branches:
      - main

jobs:
  release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
          WITH_V: false
          DEFAULT_BUMP: major

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
          TAG: ${{ steps.tag_version.outputs.new_tag }}
        shell: bash
        run: |
          echo "Creating release for tag ${TAG}"
          gh release create "${TAG}" -t "${TAG}" --generate-notes
          
