name: Cloud Custodian Policies

on:
  push:
    branches:
      - test-release-01
  pull_request:
    branches:
      - main

jobs:
  release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: minor

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.tag_version.outputs.new_tag }}
        shell: bash
        run: |
          echo "Creating release for tag ${TAG}"
          # gh release create "${TAG}" -t "${TAG}" --generate-notes

      - name: Move major version tag to current commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag is $LATEST_TAG"
          git fetch --tags
          echo "git tags"
          git tag -l
          MAJOR_VERSION="$(echo $LATEST_TAG | cut -d. -f1)"
          echo "Major version is $MAJOR_VERSION"
          # git config user.email "shivanagoudabg@gmail.com"
          git config user.name "shivanbg"
          git tag -d $LATEST_TAG
          git push origin :refs/tags/$LATEST_TAG
          git tag $LATEST_TAG ${{ github.sha }}
          git push origin --tags
          
